# Generated by Django 4.2.3 on 2024-02-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='Nbre_feuilles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='code_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
