# Generated by Django 5.0.1 on 2024-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraub',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
