# Generated by Django 4.2.3 on 2024-02-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='IBATREL',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
