# Generated by Django 4.2.3 on 2024-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_agence_ibatrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='SYS_CREATED_DATE',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
