# Generated by Django 4.2.3 on 2024-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraub_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_compte', models.CharField(max_length=100)),
                ('code_agence', models.CharField(max_length=100)),
                ('nbrchq', models.IntegerField()),
                ('nbre_feuiles', models.IntegerField()),
                ('code_transaction', models.IntegerField(default=1)),
                ('nom_de_client', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('code_devise', models.IntegerField(default=929)),
                ('code_bank', models.CharField(default='00026', max_length=10)),
                ('code_pays', models.CharField(default='02', max_length=2)),
                ('numero_de_debut', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Archives',
            },
        ),
        migrations.RemoveField(
            model_name='demchq',
            name='id',
        ),
        migrations.AlterField(
            model_name='demchq',
            name='NOOPER',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
