# Generated by Django 4.2.3 on 2024-02-13 13:51

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cheque_nbre_feuilles_alter_cheque_code_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='job',
            new_name='subj',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.FileField(null=True, upload_to=users.models.uoload_document),
        ),
    ]
