# Generated by Django 5.0.1 on 2024-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_archive_remove_demchq_id_alter_demchq_nooper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'verbose_name_plural': 'Archive'},
        ),
        migrations.AlterField(
            model_name='archive',
            name='addresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='nbrchq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='nbre_feuiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
