# Generated by Django 4.2.11 on 2024-06-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_archive_options_alter_archive_addresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraub',
            name='code_agence',
            field=models.CharField(choices=[('00001', '00001'), ('00002', '00002')], default='00001', max_length=30),
        ),
    ]
